version: "1"
rules:                      
  - base: main
    upstream:  davemorrissey:master
    mergeMethod: merge 
    mergeUnstable: false
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
